name: Example tests

on:
  push:
    branches:
      - junit4

  pull_request:
    branches:
      - junit4

  workflow_dispatch:

env:
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  QASE_TESTOPS_PROJECT: ${{ vars.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_RUN_COMPLETE: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get run title
        id: set_title
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "QASE_TESTOPS_RUN_TITLE=qase-junit4@$BRANCH_NAME: $COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Junit4 tests
        run: |
          QASE_MODE=testops mvn clean test
